### ISSUE TITLE
urlparse missing in deps

### ISSUE THREAD

**Issue by hawksight** [jusbrasil/kube-render#6]
Just trying this tool as I was about to write the same thing (or very similar).

Noticed straight away that its missing one of the deps:
```
(kube-render) ➜  example git:(master) kube-render -h
Traceback (most recent call last):
  File "/Users/pfiddes/PythonProjects/kube-render/bin/kube-render", line 7, in <module>
    from kuberender import cli_render
  File "/Users/pfiddes/PythonProjects/kube-render/lib/python3.6/site-packages/kuberender/__init__.py", line 1, in <module>
    from kuberender import render
  File "/Users/pfiddes/PythonProjects/kube-render/lib/python3.6/site-packages/kuberender/render.py", line 12, in <module>
    from .utils import load_yaml_file, make_template_path, merge_dicts
  File "/Users/pfiddes/PythonProjects/kube-render/lib/python3.6/site-packages/kuberender/utils.py", line 2, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'

(kube-render) ➜  example git:(master) pip3 list
Package    Version
---------- -------
click      6.7
dpath      1.4.0
Jinja2     2.9.6
kuberender 0.2.7
libvcs     0.2.3
MarkupSafe 1.0
pip        9.0.1
PyYAML     3.12
setuptools 38.4.0
wheel      0.30.0

(kube-render) ➜  kube-render git:(master) grep -nr 'urlparse' *
kuberender/utils.py:2:from urlparse import urlparse
kuberender/utils.py:41:    parse_result = urlparse(repo_url)

(kube-render) ➜  kube-render git:(master) pip search urlparse
bfurlparser (1.0.3)     - A blazing fast Python URL parser
giturlparse.py (0.0.5)  - A Git URL parsing module (supports parsing and rewriting)
murl (0.5.1)            - murl is a tiny wrapper for the Python module urlparse.
uritools (2.1.0)        - RFC 3986 compliant, Unicode-aware, scheme-agnostic replacement for urlparse
urlparse2 (1.1.1)       - urlparse for humans.
urlparse3 (1.1)         - urlparse3 is simple and powerful url parsing tool
urlparse4 (0.1.3)       - Performance-focused replacement for Python's urlparse module

(kube-render) ➜  kube-render git:(master) pip3 install urlparse
Collecting urlparse
  Could not find a version that satisfies the requirement urlparse (from versions: )
No matching distribution found for urlparse
```

As its not available as simply `urlparse`, is there any chance you can update to pull in the correct dependency when installed from pip3?

Or I got it running (for now) by changing [this](https://github.com/jusbrasil/kube-render/blob/master/kuberender/utils.py#L2) to:
```
from urllib.parse import urlparse
```

Using python3 and clean virtualenv:
```
(kube-render) ➜  kube-render git:(master) python3 --version
Python 3.6.4
```

**Comment by gabrielpjordao** [comment]
Hey there @hawksight,

kube-render doesn't work with Python 3 as of yet.. It's probably going to be pretty straight-forward to adapt it, though.

If you feel like, you can make the changes and open a PR. Otherwise, I can implement it (it should support Python 3 anyway).

What do you think? 

Thanks!

**Comment by hawksight** [comment]
Ah as soon as you said it, I face palmed. Sorry, just been so used to python3 by default, it explains the follow up errors etc.

I may take a look if I get any free time to do so, but can't promise anything. Maybe it's worth a quick note on the README until it is python3 compatible?
